export { configureAuthClient, getAuthClientConfig, resetAuthClientConfig } from './src/runtimeConfig.js'
export { authConfig, authConfig as defaultAuthConfig, getTimeout, getErrorMessage, checkRateLimit, circuitBreakers } from './src/config/auth.js'
export { useUserStateStore } from './src/stores/userState.js'
export { setupAuthInterceptor, setAuthRouter } from './src/auth/interceptor.js'
export { registerAuthProvider, getAuthProvider, hasAuthProvider, getAllProviderNames, callAuthProviderMethod, getAllProviderMetadata } from './src/auth/authProviders.js'
export { default as googleAuthProvider } from './src/auth/providers/google/provider.js'
export { default as supabaseAuthProvider } from './src/auth/providers/supabase/provider.js'
export { default as localAuthProvider } from './src/auth/providers/local/provider.js'

export { createLinkingSessionSnapshot, restoreLinkingSessionSnapshot } from './src/linking/sessionSnapshot.js'

export { default as PlainLoginElement } from './src/components/plain/LoginElement.vue'
export { default as PlainAccountLinking } from './src/components/plain/AccountLinking.vue'
export { default as PlainAuthErrorBoundary } from './src/components/plain/AuthErrorBoundary.vue'
export { default as PlainDrawerUserSection } from './src/components/plain/DrawerUserSection.vue'
export { default as PlainUserMenu } from './src/components/plain/UserMenu.vue'
export { default as PlainSignInPrompt } from './src/components/plain/SignInPrompt.vue'
export { default as PlainErrorBoundary } from './src/components/plain/ErrorBoundary.vue'

export { default as VuetifyLoginElement } from './src/components/vue/LoginElement.vue'
export { default as VuetifyAccountLinking } from './src/components/vue/AccountLinking.vue'
export { default as VuetifyAuthErrorBoundary } from './src/components/vue/AuthErrorBoundary.vue'
export { default as VuetifyDrawerUserSection } from './src/components/vue/DrawerUserSection.vue'
export { default as VuetifyUserMenu } from './src/components/vue/UserMenu.vue'
export { default as VuetifySignInPrompt } from './src/components/vue/SignInPrompt.vue'
export { default as VuetifyErrorBoundary } from './src/components/vue/ErrorBoundary.vue'

// Backwards-friendly aliases (default to plain)
export { default as StockLoginElement } from './src/components/plain/LoginElement.vue'
export { default as StockAccountLinking } from './src/components/plain/AccountLinking.vue'
export { default as StockAuthErrorBoundary } from './src/components/plain/AuthErrorBoundary.vue'
export { default as StockDrawerUserSection } from './src/components/plain/DrawerUserSection.vue'
export { default as StockUserMenu } from './src/components/plain/UserMenu.vue'
export { default as StockSignInPrompt } from './src/components/plain/SignInPrompt.vue'
export { default as StockErrorBoundary } from './src/components/plain/ErrorBoundary.vue'
